name: Add Application
description: Suggest an application to be added to the Awesome Windows list
labels: ["Add"]
title: "[ADD] "
assignees:
  - 0pandadev
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an application for the Awesome Windows list!
        Please fill out the form below to provide details about the application.

  - type: input
    id: app-name
    attributes:
      label: Application Name
      description: What is the name of the application?
      placeholder: e.g., Awesome App
    validations:
      required: true

  - type: input
    id: app-url
    attributes:
      label: Application URL
      description: Provide the official website or download link for the application
      placeholder: https://example.com/awesome-app
    validations:
      required: true

  - type: dropdown
    id: app-category
    attributes:
      label: Category
      description: Which category does this application belong to?
      options:
        - API Development
        - Application Launchers
        - Audio
        - Backup
        - Browsers
        - Chat Clients
        - Cloud Storage
        - Command Line Tools
        - Compression
        - Data Recovery
        - Databases
        - Developer Utilities
        - Email
        - File Management
        - Games
        - Graphics
        - IDEs
        - Networking
        - Office Suites
        - Productivity
        - Proxy and VPN Tools
        - Screen Capture
        - Security
        - System Utilities
        - Terminal
        - Text Editors
        - Version Control
        - Video
        - Virtualization
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: app-description
    attributes:
      label: Description
      description: Provide a brief description of the application and its key features
      placeholder: This application is awesome because...
    validations:
      required: true

  - type: checkboxes
    id: app-attributes
    attributes:
      label: Application Attributes
      description: Check all that apply
      options:
        - label: Open Source
        - label: Paid
        - label: Freemium (free with paid features)

  - type: input
    id: repo-url
    attributes:
      label: Repository URL
      description: If the application is open source, provide the URL to its repository (GitHub, GitLab, etc.)
      placeholder: https://github.com/example/awesome-app
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other relevant information about the application
      placeholder: e.g., system requirements, version tested, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/0pandadev/awesome-windows/blob/main/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true