name: Validate Changes

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML

      - name: Validate changes
        run: python .github/scripts/checks.py
        continue-on-error: true
        id: checks

      - name: Check alphabetical order
        run: python .github/scripts/check_sorting.py
        continue-on-error: true
        id: sorting

      - name: Summarize results
        if: always()
        run: |
          echo "## Validation Results" >> $GITHUB_STEP_SUMMARY
          echo "### Checks" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          python .github/scripts/checks.py >> $GITHUB_STEP_SUMMARY 2>&1
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "### Alphabetical Order Check" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          python .github/scripts/check_sorting.py >> $GITHUB_STEP_SUMMARY 2>&1
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Check for failures
        if: steps.checks.outcome == 'failure' || steps.sorting.outcome == 'failure'
        run: exit 1